# Generated by Django 3.2 on 2021-07-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_info',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_info', to='listings.hotelroom'),
        ),
    ]
