# Generated by Django 3.2 on 2021-07-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210724_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotel_room',
        ),
        migrations.AddField(
            model_name='reservation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_info', to='listings.hotelroom'),
        ),
    ]
