# Generated by Django 3.2 on 2021-07-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210724_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinginfo',
            options={'ordering': ['price']},
        ),
    ]
